esprit_reservation_homepage:
    path:     /
    defaults: { _controller: EspritReservationBundle:Default:index }

esprit_reservation_afficherhotel:
    path:     /afficherhotel
    defaults: { _controller: EspritReservationBundle:Hotel:AfficherHotel }

esprit_reservation_ajouterreservation:
    path:     /ajouterreservation
    defaults: { _controller: EspritReservationBundle:Reservation:AjouterReservation }

esprit_reservation_rechercherparlieux:
    path:     /rechercher{lieux}
    defaults: { _controller: EspritReservationBundle:Hotel:findHotel }
